version: '3.6'

services:
  db:
    container_name: experience_db_sql_1
    restart: always
    build:
      context: docker/postgres/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=experience
      - POSTGRES_DB=experience
      - POSTGRES_PASSWORD=experience
    volumes:
      - data_sql:/var/lib/postgresql/data
    networks:
      - experiencenet

networks:
  experiencenet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
