name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'tools/**'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Release
        uses: ridedott/release-me-action@master
        with:
          disable-changelog: true
          node-module: true
          release-branches: '["master"]'
